apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config-external
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
stringData:
  #persistence
  quarkus.datasource.jdbc.url: "jdbc:postgresql://person-service-postgres:5432/person"
  quarkus.datasource.jdbc.max-size: "10"

  database.provisioning.goals: "-import-demo-data"

  #adapter
  adapter.calleeservice.url: "http://callee-service-application:8080"
  adapter.timeout: "10000"
  adapter.failureRate: "0.5"
  adapter.openDuration: "30000"
  adapter.circuitBreaker.enabled: "true"

data:
  quarkus.datasource.username: ZXhhbXBsZS1zZXJ2aWNl
  quarkus.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==


