#https://istio.io/latest/docs/reference/config/networking/destination-rule/
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: callee-service-policy
  namespace: example-tenant-0
spec:
  host: callee-service-application
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 100


