apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
data:
  TZ: Europe/Berlin
  server.port: "${_Values_service_port}"
  server.tomcat.threads.max: "20"
  security.authentication.enabled: "false"

  #monitoring
  management.endpoint.health.show-details: always
  management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"

  #zipkin/jaeger
  spring.zipkin.service.name: "person-service-internal-tenant-${_Values_tenant_id}"

  spring.zipkin.baseUrl: "http://zipkin.monitoring:9411"
  spring.sleuth.enabled: "true"
  spring.zipkin.enabled: "true"

---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external
stringData:
  #persistence
  spring.datasource.url: "jdbc:postgresql://person-service-postgres:5432/person"
  spring.datasource.hikari.maximum-pool-size: "10"
  spring.datasource.hikari.connection-timeout: "10000"

  database.provisioning.goals: "-import-demo-data"

  #adapter
  adapter.calleeservice.url: "http://callee-service-application:8080"
  
data:
  spring.datasource.username: ZXhhbXBsZS1zZXJ2aWNl
  spring.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==

  adapter.calleeservice.user: WVdSdGFXND0=
  adapter.calleeservice.password: WVdSdGFXND0=
