apiVersion: v1
entries:
  jaeger-all:
  - apiVersion: v2
    appVersion: 1.24.0
    created: "2021-11-26T15:50:35.314496+01:00"
    description: jaeger-all
    digest: 463d48127bbde7f47ecd3371c09c069d9f11099304532da20adcbfc1c0814741
    name: jaeger-all
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/infra/infra/jaeger-all-1.24.0.tgz
    version: 1.24.0
  welcome-board:
  - apiVersion: v2
    appVersion: 1.17.10
    created: "2021-11-26T15:50:35.316234+01:00"
    description: welcome-board
    digest: 71ba5bdc5d2e2dc325bbc10fc500165240ac330ad67a76ba29263da7840846ec
    name: welcome-board
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/infra/infra/welcome-board-1.0.0.tgz
    version: 1.0.0
generated: "2021-11-26T15:50:35.313434+01:00"
