#!/bin/bash
COMMAND=$1
PROFILE=$2

function up() {
    helm install setup ./setup --set nodeName=`kubectl get nodes -o 'jsonpath={.items[*].metadata.name}'`
    kubectl patch storageclass local-storage -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
}

function down() {
    helm uninstall setup
}

function proxy() {
    echo Doing nothing !
}

if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;
elif [ "${COMMAND}" = "proxy" ]; then proxy;

else echo Doing nothing !; fi