apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
  namespace: ${_Release_namespace}
data:
  #application
  TZ: Europe/Berlin

  #PROXY
  OAUTH2_PROXY_PROVIDER: "keycloak-oidc"
  OAUTH2_PROXY_CLIENT_ID: "oauth2-proxy"
  OAUTH2_PROXY_REDIRECT_URL: "https://kubernetes/oauth2/0/callback"
  OAUTH2_PROXY_OIDC_ISSUER_URL: "http://keycloak-application.oidc:8080/auth/realms/tenant-${_Values_tenant_id}"
  
  OAUTH2_PROXY_CLIENT_SECRET: ${_Values_proxy_client_secret}
  OAUTH2_PROXY_COOKIE_SECRET: ${_Values_proxy_cookie_secret}


