apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
data:
  #application
  TZ: Europe/Berlin
  server.port: "${_Values_service_port}"
  server.tomcat.threads.max: "20"
  security.authentication.enabled: "false"

  #monitoring
  management.endpoint.health.show-details: always
  management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"

---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external

stringData:
  #adapter
  adapter.personservice.url: "http://person-service-application.example:8080"
  adapter.timeout: "10000"

data:
  adapter.personservice.user: WVdSdGFXND0=
  adapter.personservice.password: WVdSdGFXND0=



