apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
data:
  #application
  TZ: Europe/Berlin
  quarkus.http.port: "${_Values_service_port}"
  quarkus.http.io-threads: "20"

  #security
  security.authentication.enabled: "false"

  #jaeger
  quarkus.jaeger.service-name: "callee-service-tenant-${_Values_tenant_id}"

  quarkus.jaeger.endpoint: "http://jaeger-collector.monitoring:14268/api/traces"
  quarkus.jaeger.sampler-type: "probabilistic"
  quarkus.jaeger.sampler-param: "1"
  quarkus.jaeger.propagation: "b3"

---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external
data:



