replicaCount: 1

tenantId: 0
namespace: example-tenant-0

image:
  repository: "goafabric/person-service-quarkus"
  pullPolicy: IfNotPresent
  pullSecrets:

podAnnotations:
  linkerd.io/inject: disable
  sidecar.istio.io/inject: "false"

resources:
  requests:
    memory: 16M
    cpu: 250m

initContainers:
  - name: wait-for-application
    image: curlimages/curl:7.75.0
    command: ["/bin/sh","-c"]
    args: ["while [ $(curl -sw '%{http_code}' --fail --connect-timeout 1 http://person-service-application:8080/actuator/health -o /dev/null) -ne 200 ]; do sleep 2; done"]

