apiVersion: v1
entries:
  callee-service-application:
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2021-12-01T16:34:47.84603+01:00"
    description: callee-service-application
    digest: 11d998b112d7d50f172304b3fe5b8d8ffe5eead80efd3b948b7ab4c375b46446
    name: callee-service-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/quarkus/quarkus/callee-service-application-1.0.0.tgz
    version: 1.0.0
  fhir-facade-application:
  - apiVersion: v2
    appVersion: 1.0.5
    created: "2021-12-01T16:34:47.846312+01:00"
    description: fhir-facade-application
    digest: 2bda405ee6a26268bb562b837a47bdcfd2b1fbd2b073693437cd70c7ef477bf7
    name: fhir-facade-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/quarkus/quarkus/fhir-facade-application-1.0.0.tgz
    version: 1.0.0
  person-service-application:
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2021-12-01T16:34:47.84659+01:00"
    description: person-service-application
    digest: 37e6d1a046350ae8d31b7fdefdff9dbb8e37870a8a5fbd5363c190dad0c3bb82
    name: person-service-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/quarkus/quarkus/person-service-application-1.0.0.tgz
    version: 1.0.0
  person-service-batch:
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2021-12-01T16:34:47.846803+01:00"
    description: person-service-batch
    digest: df6910cbe28cc333b8882c79414329c9df7a6a3d50bc8ec051c65389a853ac98
    name: person-service-batch
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/quarkus/quarkus/person-service-batch-1.0.0.tgz
    version: 1.0.0
  person-service-postgres:
  - apiVersion: v2
    appVersion: "14.0"
    created: "2021-12-01T16:34:47.847018+01:00"
    description: person-service-postgres
    digest: 988a0284201fd03f9eebe756abeef6bee7b39d683045507447a7b78a0ab3d452
    name: person-service-postgres
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/quarkus/quarkus/person-service-postgres-1.0.0.tgz
    version: 1.0.0
generated: "2021-12-01T16:34:47.845411+01:00"
