apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${_Values_root_name}-ingress
  namespace: ${_Release_namespace}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${_Values_host_name}
      secretName: root-certificate
  rules:
    - host: ${_Values_host_name}
      http:
        paths:
          - path: /${_Values_ingress_name}
            pathType: Prefix
            backend:
              service:
                name: ${_Values_app_name}
                port:
                  name: http
           

