replicaCount: 1

tenantId: 0
ingress:
  paths: /person/{{ .Values.tenantId }}
  enabled: true

image:
  repository: "goafabric/person-service-quarkus"
  pullPolicy: IfNotPresent
  pullSecrets:

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resourcesAnnotations:
  resources:
    requests:
      memory: 16M
      cpu: 250m

  args: ["-Xmx16M", "-Djavax.net.ssl.trustStore=/usr/share/truststore/root.p12","-Djavax.net.ssl.trustStorePassword=goafabric" ]


readinessProbe:
  initialDelaySeconds: 1

service:
  type: ClusterIP
  port: 8080

initContainers:
  - name: check-db-ready
    image: postgres:14.1
    command: ['sh', '-c','until pg_isready -h person-service-postgres -p 5432;do echo waiting for database; sleep 1; done;']