replicaCount: 1
tenantId: 5a2f
namespace: example-tenant-5a2f

image:
  repository: "goafabric/callee-service-quarkus"
  tag: "1.1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"
