replicaCount: 1

tenantId: 0
namespace: example
ingress:
#  paths: /fhir
  paths: /fhir/{{ .Values.tenantId }}
  hosts: ""
  enabled: true

image:
  repository: "goafabric/fhir-facade-quarkus"
  pullPolicy: IfNotPresent
  pullSecrets: 

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resourcesAnnotations:
  resources:
    requests:
      memory: 16M
      cpu: 250m

  args: ["-Xmx32M"]

readinessProbe:
  initialDelaySeconds: 1

service:
  type: ClusterIP
  port: 8080
