apiVersion: v1
kind: Service
metadata:
  name: ${_Values_app_name}
  namespace: ${_Release_namespace}
  labels:
    app: ${_Values_app_name}
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
    protocol: TCP