apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config-files
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  00_pg_statements.sql: |-
    CREATE EXTENSION pg_stat_statements;
