spring:
  cloud:
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay=Bearer
      routes:
        - id: core_route
          uri: http://application:50800
          predicates:
            - Path=/core/**
          filters:
            - RewritePath=/core/(?<path>.*), /$\{path}

        - id: catalog_route
          uri: http://catalog-service:50600
          predicates:
            - Path=/catalog/**
          filters:
            - RewritePath=/catalog/(?<path>.*), /$\{path}

#spring.webflux.base-path: "/gateway"