apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${_Values_app_name}
  name: ${_Values_app_name}
  namespace: oidc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${_Values_app_name}
  template:
    metadata:
      labels:
        app: ${_Values_app_name}
    spec:
      containers:
      - args:
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        envFrom:
          - configMapRef:
              name: ${_Values_app_name}-config

        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: ${_Values_app_name}
        ports:
        - containerPort: 4180
          protocol: TCP
