apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${_Values_app_name}
  name: ${_Values_app_name}
  namespace: ${_Release_namespace}
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    app: oauth2-proxy
