apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: callee-service-policy
  namespace: example
spec:
  host: callee-service-application.example
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      tcp:
#        maxConnections: 100
        connectTimeout: 1ms
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s #sliding window
      baseEjectionTime: 30s #time until the cb keeps open
      maxEjectionPercent: 100


#https://istio.io/latest/docs/reference/config/networking/destination-rule/