apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
data:
  #application
  TZ: Europe/Berlin
  quarkus.http.port: "${_Values_service_port}"
  quarkus.http.io-threads: "20"

  #security
  security.authentication.enabled: "false"

  #jaeger
  quarkus.jaeger.service-name: "person-service-tenant-${_Values_tenant_id}"

  quarkus.jaeger.endpoint: "http://jaeger-collector.monitoring:14268/api/traces"
  quarkus.jaeger.sampler-type: "probabilistic"
  quarkus.jaeger.sampler-param: "1"
  quarkus.jaeger.propagation: "b3"

---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external
stringData:
  #persistence
  quarkus.datasource.jdbc.url: "jdbc:postgresql://person-service-postgres:5432/person"
  quarkus.datasource.jdbc.max-size: "10"

  database.provisioning.goals: "-import-demo-data"
  
  #adapter
  adapter.calleeservice.url: "http://callee-service-application:8080"
  adapter.timeout: "10000"
  adapter.failureRate: "0.5"
  adapter.openDuration: "30000"
  adapter.circuitBreaker.enabled: "true"

data:
  quarkus.datasource.username: ZXhhbXBsZS1zZXJ2aWNl
  quarkus.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==

  adapter.calleeservice.user: WVdSdGFXND0=
  adapter.calleeservice.password: WVdSdGFXND0=

  security.encryption.key: "MjAzZmVmOTAtYWVhZC00NWNhLTgzMGUtY2E4NzhiYjRlOTg3" #this needs to be changed during first deployment to an unique value

