apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
data:
  TZ: Europe/Berlin
  server.port: "${_Values_service_port}"

  #monitoring
  management.database.monitoring.enabled: "true"
  management.endpoints.web.exposure.include: "info,health,heapdump,circuitbreakers,prometheus"
  management.endpoint.health.show-details: always

  server.tomcat.threads.max: "20"
  security.authentication.enabled: "false"

---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external
data:



