apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config-external
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
stringData:
  POSTGRES_DB: person
data:
  POSTGRES_USER: ZXhhbXBsZS1zZXJ2aWNl
  POSTGRES_PASSWORD: Y3JOYjJaNm12QnlTUkt3dQ==

  #echo -n example-user | base64
  #echo -n crNb2Z6mvBySRKwu | base64
  #echo -n Y3JOYjJaNm12QnlTUkt3dQ== | base64 -d