apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
data:
  #application
  TZ: Europe/Berlin
  quarkus.http.port: "${_Values_service_port}"
  quarkus.http.io-threads: "20"
  security.authentication.enabled: "false"

---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external
stringData:
  #persistence
  quarkus.datasource.jdbc.url: "jdbc:postgresql://person-service-postgres:5432/person"
  quarkus.datasource.jdbc.max-size: "10"

  database.provisioning.goals: "-import-demo-data -terminate"
  
  #adapter
  adapter.calleeservice.url: "http://callee-service-application.example:8080"
  adapter.timeout: "10000"
  adapter.failureRate: "0.5"
  adapter.openDuration: "30000"

data:
  quarkus.datasource.username: ZXhhbXBsZS1zZXJ2aWNl
  quarkus.datasource.password: Y3JOYjJaNm12QnlTUkt3dQ==

  adapter.calleeservice.user: WVdSdGFXND0=
  adapter.calleeservice.password: WVdSdGFXND0=
