kind: Namespace
apiVersion: v1
metadata:
  name: kubernetes-dashboard
  labels:
    istio-injection: disabled
    secret-sync: enabled

---

kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
  labels:
    istio-injection: disabled
    secret-sync: enabled

---

kind: Namespace
apiVersion: v1
metadata:
  name: oidc
  labels:
    istio-injection: disabled
    secret-sync: enabled

---

kind: Namespace
apiVersion: v1
metadata:
  name: istio-system
  labels:
    istio-injection: disabled
    secret-sync: enabled
