#https://banzaicloud.com/blog/istio-sidecar/
#https://medium.com/geekculture/watch-out-for-this-istio-proxy-sidecar-memory-pitfall-8dbd99ea7e9d
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: example
spec:
  egress:
    - hosts:
        - ./*
        - istio-system/*