apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  server.port: "{{ .Values.service.port }}"
  spring.config.location: "/usr/share/config/"

  #security
  security.authentication.enabled: "true"

  spring.security.oauth2.authorization-uri: "https://{{ .Values.ingress.hosts}}/oidc/realms/tenant-{tenantId}/protocol/openid-connect/auth"
  spring.security.oauth2.logout-uri: "https://{{ .Values.ingress.hosts}}/oidc/realms/tenant-{tenantId}/protocol/openid-connect/logout"
  spring.security.oauth2.base-uri: "http://keycloak-application.oidc:8080/oidc/realms/tenant-{tenantId}/protocol/openid-connect"
  spring.security.oauth2.user-name-attribute: "preferred_username"

  spring.security.oauth2.path-matchers: "/callee/**,/core/**,/catalog/**"

  spring.security.oauth2.client-id: "oauth2-proxy"
  spring.security.oauth2.client-secret: "none"

  #monitoring
  management.endpoint.health.show-details: always
  management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"

  #zipkin/jaeger
  spring.application.name: "{{ include "application.fullname" . }}"
  management.otlp.tracing.endpoint: "http://otlp.monitoring:4318/v1/traces"
  management.tracing.sampling.probability: "1.0"
  logging.level.io.opentelemetry: "INFO"