apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  server.port: "{{ .Values.service.port }}"
  server.tomcat.threads.max: "20"
  server.forward-headers-strategy: FRAMEWORK

  #keycloak
  keycloak.uri: "http://keycloak-application.oidc:8080/oidc"
  keycloak.client-id: "apisix-client"
  keycloak.client-secret: "t5LtTEhVEyd46acNmBa3iylPtLA2cZl3"

  #monitoring
  management.endpoint.health.show-details: always
  management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"

  #zipkin/jaeger
  spring.application.name: "{{ include "application.fullname" . }}"
  management.otlp.tracing.endpoint: "http://otlp.monitoring:4318/v1/traces"
  management.tracing.sampling.probability: "1.0"
  logging.level.io.opentelemetry: "INFO"