apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: callee-service-virtual
spec:
  hosts:
    - callee-service-application
  http:
    - route:
        - destination:
            host: callee-service-application
            subset: v1
      timeout: 1s

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: callee-service-destination
spec:
  host: callee-service-application
  subsets:
    - name: v1
      labels:
        version: v1
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 10s
      baseEjectionTime: 15s
      maxEjectionPercent: 100