version: "3"

services:
  proxy:
    container_name: ${_Values_root_name}-application
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    command:
      - --email-domain=*
      - --upstream=file:///dev/null
      - --http-address=0.0.0.0:4180
      - --reverse-proxy=true
      - --set-xauthrequest=true
#      - --proxy-prefix=/oauth2
#      - --proxy-prefix=/oauth2/${_Values_tenant_id}
    restart: 'no'
    ports:
      - "4180:4180"
    networks:
      - ${_Values_root_name}-net
    environment:
      #application
      TZ: Europe/Berlin

      OAUTH2_PROXY_PROVIDER: "oidc"
      OAUTH2_PROXY_CLIENT_ID: "oauth2-proxy"
      OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: "true"

      OAUTH2_PROXY_REDIRECT_URL: "http://localhost:8080/oauth2/callback"

      OAUTH2_PROXY_OIDC_ISSUER_URL: "http://localhost:30200/oidc/auth/realms/tenant-${_Values_tenant_id}"
      OAUTH2_PROXY_LOGIN_URL: "http://localhost:30200/oidc/auth/realms/tenant-${_Values_tenant_id}/protocol/openid-connect/auth"

      OAUTH2_PROXY_REDEEM_URL: "http://host.docker.internal:30200/oidc/auth/realms/tenant-${_Values_tenant_id}/protocol/openid-connect/token"
      OAUTH2_PROXY_OIDC_JWKS_URL: "http://host.docker.internal:30200/oidc/auth/realms/tenant-${_Values_tenant_id}/protocol/openid-connect/certs"

      OAUTH2_PROXY_CLIENT_SECRET: none
      OAUTH2_PROXY_COOKIE_SECRET: SvJIUgqBKxOYSxJwFREiOg==

networks:
  oauth2-proxy-net: