kind: ConfigMap
apiVersion: v1
metadata:
  name: loki-loki-stack
  namespace: monitoring
  labels:
    app: loki-stack
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
data:
  loki-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      version: 1
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus.istio-system:9090
      version: 1
