version: "3.7"

services:
  person-service:
    container_name: ${_Values_root_name}-application
    image: simaofsilva/keycloak:15.0.2
#    image: svefors/keycloak-x:12.0.2
    restart: 'no'
    ports:
      - "${_Values_service_port}:${_Values_service_port}"
#    command: ["start-dev"]

    networks:
      - ${_Values_root_name}-net
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSSWORD=admin
      #Database
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-postgres
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    depends_on:
      - postgres

  postgres:
    container_name: ${_Values_root_name}-postgres
    image: postgres:13.4
    restart: 'no'
    ports:
      - 5432
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    command: postgres -c 'shared_buffers=128MB' -c 'max_connections=30' -c 'shared_preload_libraries=pg_stat_statements'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ${_Values_root_name}-net

volumes:
    pgdata:

networks:
  keycloak-net:
    driver: bridge