version: "3.7"

services:
  keycloak:
    container_name: ${_Values_root_name}-application
    image:  ${_Values_image_repository}${_Values_image_native}:${_Values_image_tag}
    restart: 'no'
    ports:
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - ${_Values_root_name}-net
    environment:
      #application
      - TZ=Europe/Berlin
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

volumes:
    tmp:
    applogs:

networks:
  jaeger-net:
    driver: bridge