replicaCount: 1

tenantId: 0
namespace: example-tenant-0
ingressName: person/0

host:
  name: ""

image:
  repository: "goafabric/person-service-quarkus"
  tag: "1.1.1"
  pullPolicy: IfNotPresent
  pullSecrets:

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resources:
  requests:
    memory: 16M
    cpu: 250m

readinessProbe:
  initialDelaySeconds: 1

service:
  type: ClusterIP
  port: 8080

initContainers:
  - name: check-db-ready
    image: postgres:14.0
    command: ['sh', '-c','until pg_isready -h person-service-postgres -p 5432;do echo waiting for database; sleep 1; done;']