replicaCount: 1

tenantId: 0
namespace: example-tenant-0
ingress:
  paths: /callee/0
  hosts: ""


image:
  repository: "goafabric/callee-service"
  pullPolicy: IfNotPresent
  pullSecrets: 

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "false"

resources:
  requests:
    memory: 128M
    cpu: 250m

readinessProbe:
  initialDelaySeconds: 2

service:
  type: ClusterIP
  port: 8080




