replicaCount: 1

tenantId: 0
namespace: example-tenant-0
ingressName: callee/0

host:
  name: ""

image:
  repository: "goafabric/callee-service"
  tag: "1.1.0"
  pullPolicy: IfNotPresent
  pullSecrets: 

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resources:
  requests:
    memory: 128M
    cpu: 250m

readinessProbe:
  initialDelaySeconds: 2

service:
  type: ClusterIP
  port: 8080




