apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: example2
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
    - from:
        - podSelector: {}