apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  server.port: "{{ .Values.service.port }}"
  server.tomcat.threads.max: "20"
  server.forward-headers-strategy: FRAMEWORK

  #security
  security.authentication.enabled: "false"

  #monitoring
  management.endpoint.health.show-details: always
  management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"

  #rabbit
  spring.rabbitmq.host: "rabbitmq"

  #ssl
  {{ if .Values.readinessProbe.scheme }} {{ if eq .Values.readinessProbe.scheme "HTTPS" }}
  server.ssl.key-store: "/usr/share/truststore/callee-service-application.p12"
  server.ssl.key-store-password: "kubernetes"
  {{ end }} {{ end }}

