apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config-log
data:
  #log levels
  quarkus.log.level: "INFO"
#  quarkus.log.category."org.goafabric".level: "INFO"
#  quarkus.log.category."org.flywaydb.core".level: "INFO"
#  quarkus.log.category."org.hibernate".level: "INFO"

  #log standard settings

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config-files
data: