apiVersion: v1
entries:
  callee-service-application:
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2021-12-01T16:45:43.08715+01:00"
    description: callee-service-application
    digest: ffb8d716ee32da010986db3a3b2abaa7ef11f1937524c433a724c621e3cd4b4a
    name: callee-service-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/quarkus/callee-service-application-1.0.0.tgz
    version: 1.0.0
  fhir-facade-application:
  - apiVersion: v2
    appVersion: 1.0.5
    created: "2021-12-01T16:45:43.087356+01:00"
    description: fhir-facade-application
    digest: 4d105e23604f76b8f72d23d6bc2625042de39ac123e3e625ad707e255f9dd68d
    name: fhir-facade-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/quarkus/fhir-facade-application-1.0.0.tgz
    version: 1.0.0
  person-service-application:
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2021-12-01T16:45:43.087585+01:00"
    description: person-service-application
    digest: a42f2c0b3a12b7beaf07aaa94ea79e86cb164320998c5a81526dd0feb2d39700
    name: person-service-application
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/quarkus/person-service-application-1.0.0.tgz
    version: 1.0.0
  person-service-batch:
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2021-12-01T16:45:43.087775+01:00"
    description: person-service-batch
    digest: 9938a30614bd058fefaaa72920818239dd28d54e40f4e349b6790ce4685d085d
    name: person-service-batch
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/quarkus/person-service-batch-1.0.0.tgz
    version: 1.0.0
  person-service-postgres:
  - apiVersion: v2
    appVersion: "14.0"
    created: "2021-12-01T16:45:43.087958+01:00"
    description: person-service-postgres
    digest: c6bfa264de34f67835983cdbe921a4a6843869b0536e816ff218e8bb0142e334
    name: person-service-postgres
    type: application
    urls:
    - https://goafabric.github.io/example-konstruction-kit/helm/charts/example/quarkus/person-service-postgres-1.0.0.tgz
    version: 1.0.0
generated: "2021-12-01T16:45:43.08685+01:00"
