apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  server.port: "{{ .Values.service.port }}"
  server.tomcat.threads.max: "20"
  server.forward-headers-strategy: FRAMEWORK

  #users
  spring.security.authorization.base-uri: "/oidc"
  spring.security.authorization.clients: "oauth2-proxy:none"
  spring.security.authorization.users: "user1:user1,user2:user2,user3:user3,user4:user4,admin:admin"