#!/bin/bash
COMMAND=$1
PROFILE=$2

function up() {
    helm repo add apisix https://apache.github.io/apisix-helm-chart
    #helm repo add bitnami https://charts.bitnami.com/bitnami  > /dev/null
    helm repo update
    # TODO using older version because of this bug: https://github.com/apache/apisix/pull/10066
    # values for latest version of apisix: --set service.type=LoadBalancer,apisix.ssl.enabled=true,ingress-controller.enabled=true \
    helm install apisix apisix/apisix --version 1.3.1 \
      --set gateway.type=NodePort,gateway.tls.containerPort=443,gateway.tls.enabled=true,pluginAttrs.redirect.https_port=443,ingress-controller.enabled=true \
      --namespace ingress-apisix \
      --create-namespace

    helm install apisix-dashboard apisix/apisix-dashboard --namespace ingress-apisix

    helm install apisix-tls ./apisix-tls --set hostname=`kubectl get configmaps cluster-config -o jsonpath='{.data.hostname}' -n default` \
      --namespace ingress-apisix
}

function down() {
    helm uninstall apisix-tls --namespace ingress-apisix
    helm uninstall apisix-dashboard --namespace ingress-apisix
    helm uninstall apisix --namespace ingress-apisix && kubectl delete namespace ingress-apisix
}

function proxy() {
      kubectl -n ingress-apisix port-forward service/apisix-dashboard 9090:80
}

if   [ "${COMMAND}" = "init" ] ; then up;
elif [ "${COMMAND}" = "restart" ] ; then down && up;
elif [ "${COMMAND}" = "prune" ]; then down;
elif [ "${COMMAND}" = "proxy" ]; then proxy;

else echo Doing nothing !; fi