replicaCount: 1

tenantId: 0
namespace: example-tenant-0

image:
  repository: "goafabric/person-service-quarkus"
  tag: "1.1.1"
  pullPolicy: IfNotPresent

podAnnotations:
  linkerd.io/inject: disable
  sidecar.istio.io/inject: "false"

resources:
  requests:
    memory: 16M
    cpu: 250m

initContainers:
  - name: check-db-ready
    image: postgres:14.0
    command: ['sh', '-c','until pg_isready -h person-service-postgres -p 5432;do echo waiting for database; sleep 1; done;']



