replicaCount: 1

tenantId: 5a2f
ingress:
  paths: /callee/{{ .Values.tenantId }}
  enabled: true

image:
  repository: "goafabric/callee-service"
  pullPolicy: IfNotPresent
  pullSecrets: 

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resourcesAnnotations:
  resources:
    requests:
      memory: 128M
      cpu: 250m

  command: ["java", "-Xms128M", "-Xmx128M", "-cp", "/app/resources:/app/classes:/app/libs/*", "org.goafabric.calleeservice.Application"]

nativeAnnotations:
  resources:
    requests:
      memory: 64M
      cpu: 250m

  args: ["-Xmx64M"]

readinessProbe:
  initialDelaySeconds: 2

service:
  type: ClusterIP
  port: 8080




