apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}-config-external
  labels:
    {{- include "application.labels" . | nindent 4 }}

stringData:
  #adapter
  adapter.personservice.url: "http://person-service-application.example-tenant-%TENANT_ID%:8080"

  adapter.timeout: "10000"
  resilience4j.circuitbreaker.configs.default.slowCallDurationThreshold: "10000"
  resilience4j.circuitbreaker.configs.default.waitDurationInOpenState: "30s"
  resilience4j.circuitbreaker.configs.default.failureRateThreshold: "50"
  resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls: "10"
  #  resilience4j.circuitbreaker.configs.default.ignoreExceptions: "java.lang.Exception"

  multi.tenancy.enabled: "true"


data:
  adapter.personservice.user: WVdSdGFXND0=
  adapter.personservice.password: WVdSdGFXND0=