apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
data:
  #application
  TZ: Europe/Berlin
  quarkus.http.port: "${_Values_service_port}"
  quarkus.http.io-threads: "20"
  security.authentication.enabled: "false"

  profiles.active: "remote"

---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external
stringData:
  #adapter
  adapter.personservice.url: "http://person-service-application:8080"
  adapter.timeout: "10000"
  adapter.failureRate: "0.5"
  adapter.openDuration: "30000"

data:
  adapter.personservice.user: WVdSdGFXND0=
  adapter.personservice.password: WVdSdGFXND0=
