version: "3.7"

services:
  application:
    container_name: ${_Values_root_name}-application
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    command:
      - --email-domain=*
    restart: 'no'
    ports:
      - "4180:4180"
    environment:
      #application
      TZ: Europe/Berlin

      # oauth2proxy generic config
      OAUTH2_PROXY_UPSTREAM: "file:///dev/null"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"

      # oauth2proxy provider config
      # https://github.com/settings/developers
      OAUTH2_PROXY_PROVIDER: "github"
      OAUTH2_PROXY_CLIENT_ID: "028cf7cd4281313938a0"
      OAUTH2_PROXY_CLIENT_SECRET: "2d79fbf8d9a4f1c0861fc8aa5b41d835d760212b"

      # docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
      OAUTH2_PROXY_COOKIE_SECRET: SvJIUgqBKxOYSxJwFREiOg==

    networks:
      - ${_Values_root_name}-net

volumes:
    tmp:
    applogs:
    pgdata:

networks:
  oauth2proxy-net:
    driver: bridge