replicaCount: 1

tenantId: 0
namespace: example-tenant-0
rootName: person-service

host:
  name: ""

image:
  repository: "postgres"
  tag: "14.0"
  pullPolicy: IfNotPresent

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resources:
  requests:
    memory: 128M
    cpu: 250m
  limits:
    cpu: 500m

readinessProbe:
  initialDelaySeconds: 1

service:
  type: ClusterIP
  port: 5432

postgres:
  maxConnections: 30