replicaCount: 1

tenantId: 0
namespace: example-tenant-0
ingressName: callee/0

host:
  name: ""

image:
  repository: "goafabric/callee-service-quarkus"
  tag: "1.1.1"
  pullPolicy: IfNotPresent

podAnnotations:
  linkerd.io/inject: enabled
  sidecar.istio.io/inject: "true"

resources:
  requests:
    memory: 16M
    cpu: 250m

readinessProbe:
  initialDelaySeconds: 1

service:
  type: ClusterIP
  port: 8080




