apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /jaeger/$2

    nginx.ingress.kubernetes.io/enable-modsecurity: "true"

    # basic auth
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "authentication-secret"

    # oidc auth
    #nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/$http_x_tenantid/start?rd=$escaped_request_uri"
    #nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/$http_x_tenantid/auth" #"https://$host/oauth2/$http_x_tenantid/auth"

    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.hosts}}
      secretName: root-certificate
  rules:
    - host: {{ .Values.ingress.hosts}}
      http:
        paths:
          - path: /jaeger(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: tracing
                port:
                  number: 80