kind: Namespace
apiVersion: v1
metadata:
  name: example
  labels:
     istio.io/dataplane-mode: ambient

---

kind: Namespace
apiVersion: v1
metadata:
  name: example-tenant-0
  labels:
     istio.io/dataplane-mode: ambient

---

kind: Namespace
apiVersion: v1
metadata:
  name: example-tenant-5a2f
  labels:
     istio.io/dataplane-mode: ambient