apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config-log
  namespace: {{ .Values.namespace }}
data:
  #log levels
  quarkus.log.level: "INFO"
#  quarkus.log.category."org.goafabric".level: "INFO"
#  quarkus.log.category."org.flywaydb.core".level: "INFO"
#  quarkus.log.category."org.hibernate".level: "INFO"

  #log file settings
  quarkus.log.file.enable: "true"
  quarkus.log.file.rotation.max-file-size: "10M"
  quarkus.log.file.path: "/usr/share/logs/application.log"
  quarkus.log.file.format: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n%throwable"
