{{- $applicationFullname := include "application.fullname" . -}}
{{- $ingressHosts := .Values.ingress.hosts -}}
{{- range $tenantID := .Values.ingress.tenantIDs }}
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ $applicationFullname }}-{{ $tenantID }}
spec:
  http:
    - name: {{ $applicationFullname }}-{{ $tenantID }}
      match:
        hosts:
          - {{ $ingressHosts }}
        paths:
          - /{{ $tenantID }}
          - /{{ $tenantID }}/*
      backends:
        - serviceName: welcome-board
          servicePort: 8080
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
        - name: openid-connect
          enable: true
          config:
            client_id: oauth2-proxy
            client_secret: none
            discovery: https://{{ $ingressHosts }}/oidc/realms/tenant-{{ $tenantID }}/.well-known/openid-configuration
            realm: tenant-{{ $tenantID }}
            access_token_in_authorization_header: false
            set_id_token_header: false
            set_userinfo_header: false
            redirect_uri: "/{{ $tenantID }}/redirect_uri"
            logout_path: "/{{ $tenantID }}/logout"
            ssl_verify: false
        - name: proxy-rewrite
          enable: true
          config:
            regex_uri:
              - /{{ $tenantID }}/(.*)
              - /
---
{{- end }}