apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ include "application.fullname" . }}
spec:
  http:
    - name: {{ include "application.fullname" . }}
      match:
        hosts:
          - {{.Values.ingress.hosts}}
        paths:
          - /*
      backends:
        - serviceName: welcome-board
          servicePort: 8080
      plugins:
        - name: redirect
          enable: true
          config:
            http_to_https: true
        - name: openid-connect
          enable: true
          config:
            client_id: oauth2-proxy
            client_secret: none
            discovery: https://{{.Values.ingress.hosts}}/oidc/realms/tenant-0/.well-known/openid-configuration
            realm: tenant-0
            access_token_in_authorization_header: false
            set_id_token_header: false
            set_userinfo_header: false
            redirect_uri: "/redirect_uri"
            ssl_verify: false