apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
  namespace: ${_Release_namespace}
data:
  #application
  TZ: Europe/Berlin

  KC_HTTP_RELATIVE_PATH: "oidc/auth"
  KC_PROXY: "edge"
  KC_HOSTNAME_STRICT: "false"

  #database
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://keycloak-postgres/keycloak"

---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external
  namespace: ${_Release_namespace}
data:
  #keycloak admin user
  KEYCLOAK_USER: "YWRtaW4="
  KEYCLOAK_PASSWORD: "YWRtaW4="

  #keycloak.x admin user
  KEYCLOAK_ADMIN: "YWRtaW4="
  KEYCLOAK_ADMIN_PASSWORD: "YWRtaW4="

  #database user
  KC_DB_USERNAME: "a2V5Y2xvYWs="
  KC_DB_PASSWORD: "a2V5Y2xvYWs="

