apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
  namespace: ${_Release_namespace}
data:
  #application
  TZ: Europe/Berlin

#  PROXY_ADDRESS_FORWARDING: "true"
#  KEYCLOAK_FRONTEND_URL: "https://${_Values_host_name}/${_Values_ingress_name}/auth"

  #database
  DB_VENDOR: "POSTGRES"
  DB_ADDR: "keycloak-postgres"

---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external
  namespace: ${_Release_namespace}
data:
  #keycloak admin user
  KEYCLOAK_USER: "YWRtaW4="
  KEYCLOAK_PASSWORD: "YWRtaW4="

  #keycloak.x admin user
  KEYCLOAK_ADMIN: "YWRtaW4="
  KEYCLOAK_ADMIN_PASSWORD: "YWRtaW4="

  #database user
  DB_USER: "a2V5Y2xvYWs="
  DB_PASSWORD: "a2V5Y2xvYWs="

