apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${_Values_app_name}
  namespace: ${_Release_namespace}
  labels:
    app: ${_Values_app_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${_Values_app_name}
  template:
    metadata:
      labels:
        app: ${_Values_app_name}
    spec:
      containers:
      - name: ${_Values_app_name}
        image: quay.io/keycloak/keycloak:17.0.1 #svefors/keycloak-x:12.0.2

        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443

        envFrom:
          - configMapRef:
              name: ${_Values_app_name}-config
          - secretRef:
              name: ${_Values_app_name}-config-external

        args: ["start --auto-build --db=postgres --http-enabled=true --http-port=8080 --http-host=0.0.0.0 --hostname=localhost:8080 --hostname-strict-https=false"]

        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
          initialDelaySeconds: 5
