apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  server.port: "{{ .Values.service.port }}"
  server.tomcat.threads.max: "20"
  server.forward-headers-strategy: FRAMEWORK

  #security
  security.authentication.enabled: "false"

  #monitoring
  management.endpoint.health.show-details: always
  management.endpoints.web.exposure.include: "health,heapdump,circuitbreakers,prometheus"

  #zipkin/jaeger
  spring.zipkin.service.name: "{{ include "application.fullname" . }}-tenant-{{ .Values.tenantId }}"

  spring.zipkin.baseUrl: "http://zipkin.monitoring:9411"
  spring.sleuth.enabled: "true"
  spring.zipkin.enabled: "true"

  #persistence
  spring.datasource.url: "jdbc:postgresql://person-service-postgres:5432/person"
  spring.datasource.hikari.maximum-pool-size: "10"
  spring.datasource.hikari.connection-timeout: "10000"

  database.provisioning.goals: ""

  #adapter

  adapter.calleeservice.url: "https://callee-service-application:8080"
  #adapter.calleeservice.url: "https://kubernetes/callee/0"

#  my.trust-store: "classpath:truststore/root.p12"
#  my.trust-store-password: "goafabric"
  
  my.trust-store: "/usr/share/truststore/root.p12"
  my.trust-store-password: "goafabric"

#  server.ssl.trust-store: "/usr/share/truststore/root.p12"
#  server.ssl.trust-store-password: "goafabric"