apiVersion: v1
kind: ConfigMap
metadata:
  name: ${_Values_app_name}-config
  namespace: ${_Release_namespace}
data:
  #application
  TZ: Europe/Berlin


  # oauth2proxy generic config
  OAUTH2_PROXY_UPSTREAM: "file:///dev/null"
  OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
  OAUTH2_PROXY_REVERSE_PROXY: "true"
  OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
  OAUTH2_PROXY_PROXY_PREFIX: "/${_Values_ingress_name}"

  # oauth2proxy provider config
  OAUTH2_PROXY_PROVIDER: "oidc"
  OAUTH2_PROXY_CLIENT_ID: "oauth2-proxy"
  OAUTH2_PROXY_SKIP_OIDC_DISCOVERY: "true"

  OAUTH2_PROXY_REDIRECT_URL: "https://${_Values_host_name}/oauth2/${_Values_tenant_id}/callback"
  OAUTH2_PROXY_LOGIN_URL: "https://${_Values_host_name}/oidc/auth"

  OAUTH2_PROXY_OIDC_ISSUER_URL: "http://spring-auth-server-application:8080"
  OAUTH2_PROXY_OIDC_JWKS_URL: "http://spring-auth-server-application:8080/oidc/certs"
  OAUTH2_PROXY_REDEEM_URL: "http://spring-auth-server-application:8080/oidc/token"




---

apiVersion: v1
kind: Secret
metadata:
  name: ${_Values_app_name}-config-external
  namespace: ${_Release_namespace}
data:
  OAUTH2_PROXY_CLIENT_SECRET: ${_Values_proxy_client_secret}
  OAUTH2_PROXY_COOKIE_SECRET: ${_Values_proxy_cookie_secret}

