apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  #application
  TZ: Europe/Berlin
  quarkus.http.port: "{{ .Values.service.port }}"
  quarkus.http.io-threads: "20"

  #security
  security.authentication.enabled: "false"

  #jaeger
  quarkus.jaeger.service-name: "callee-service-tenant-{{ .Values.tenantId }}"

  quarkus.jaeger.endpoint: "http://jaeger-collector.monitoring:14268/api/traces"
  quarkus.jaeger.sampler-type: "probabilistic"
  quarkus.jaeger.sampler-param: "1"
  quarkus.jaeger.propagation: "b3"

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config-external
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application.labels" . | nindent 4 }}



