kind: Namespace
apiVersion: v1
metadata:
  name: example
  labels:
    istio-injection: enabled
#    secret-sync: enabled

---

kind: Namespace
apiVersion: v1
metadata:
  name: example-tenant-0
  labels:
    istio-injection: enabled
#    secret-sync: enabled

---

kind: Namespace
apiVersion: v1
metadata:
  name: example-tenant-5a2f
  labels:
    istio-injection: enabled
#    secret-sync: enabled