apiVersion: v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>Cluster Landing Page</title>
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,700;1,100&display=swap"
              rel="stylesheet">
        <style>
            body, h1, h2, h3, h4, h5, h6 {
                margin: 0;
            }

            ul {
                margin: 16px 0;
                padding-left: 40px;
            }

            li {
                list-style: none;
            }

            html {
                background-color: #0099ff;
                background-size: cover;
            }

            body {
                color: #ffffff;
                font-family: 'Roboto', sans-serif;
                padding-top: 100px;
                text-align: center;
            }

            .title {
                font-size: 60px;
                font-weight: 300;
            }

            .subtitle {
                font-size: 20px;
                font-weight: 100;
                font-style: italic;
            }

            .box {
                backdrop-filter: blur(5px);
                background: rgba(66, 66, 66, 0.25);
                border: 2px solid #ffffff;
                box-sizing: border-box;
                margin: 75px auto 0;
                max-width: 1024px;
                padding: 25px;
                width: 100%;
            }

            .links-container {
                box-sizing: border-box;
                display: flex;
                flex-wrap: wrap;
                margin-top: 25px;
                width: 100%;
            }

            .links {
                flex: 33%;
                margin: 25px 0;
                text-align: left;
            }

            .links h6 {
                font-size: 30px;
                font-weight: 300;
                padding-left: 79px;
                text-transform: uppercase;
            }

            .links a {
                align-items: center;
                color: #ffffff;
                display: inline-flex;
                font-size: 16px;
                margin: 5px;
                text-decoration: none;
            }

            .links a:hover {
                text-decoration: underline;
            }

            .links a img {
                height: 24px;
                margin-right: 10px;
                width: 24px;
            }
            p {
              height: 1px;
              border-bottom: 1px dashed #ffffff54;
            }
        </style>
    </head>
    <body>
    <div class="box">
        <h1 class="title">Welcome to the Example Cluster 1.0.6</h1>
        <h2 class="subtitle">Your best course would be to tread lightly ...</h2>

        <div class="links-container">
            <div class="links">
                <h6>Dashboards</h6>
                <ul>
                    <p></p>
                    <li>
                        <a href="/dashboard/#" target="_blank">
                            <span>☸️ Kubernetes Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a href="/kiali/" target="_blank">
                            <span>⛵ Istio Dashboard</span>
                        </a>
                    </li>
                    <p></p>
                    <li>
                        <a href="/jaeger/" target="_blank">
                            <span>🏹 Jaeger</span>
                        </a>
                    </li>
                    <li>
                        <a href="/grafana/" target="_blank">
                            <span>📊 Loki</span>
                        </a>
                    </li>
                    <p></p>
                    <li>
                        <a href="/oidc/auth/" target="_blank">
                            <span>🔐 Keycloak</span>
                        </a>
                        <a href="/welcome/proxy_logout.html?tenant=0" target="_blank">
                            <span>➡️ Logout</span>
                        </a>
                    </li>
                    <p></p>
                    <li>
                        <a href="/event/" target="_blank">
                            <span>🐰 Event Dispatcher</span>
                        </a>
                        <a href="/rabbitmq/" target="_blank">
                            <span>🐰 RabbitMQ</span>
                        </a>
                    </li>

                </ul>
            </div>

            <div class="links">
                <h6>Example 0</h6>
                <ul>
                    <p></p>
                    <li>
                        <a href="/fhir/" target="_blank">
                            <span>🔥 FHIR Facade</span>
                        </a>
                    </li>
                    <li>
                        <a href="/fhir/actuator/health" target="_blank">
                            <span>🖥️ Health</span>
                        </a>
                    </li>
                    <p></p>
                    <li>
                        <a href="/person/0/" target="_blank">
                            <span>🌍 Person Service</span>
                        </a>
                    </li>
                    <li>
                        <a href="/person/0/actuator/health" target="_blank">
                            <span>🖥️ Health</span>
                        </a>
                    </li>
                    <p></p>
                    <li>
                        <a href="/callee/0/" target="_blank">
                            <span>📢 Callee Service</span>
                        </a>
                    </li>
                    <li>
                        <a href="/callee/0/actuator/health" target="_blank">
                            <span>🖥️ Health</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    </body>
    </html>
  proxy_login.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1 class="title">Login</h1>

    <script>

    function login() {
        const params = new URLSearchParams(window.location.search)
        const tenant = params.get('tenant')

        if (tenant == null || tenant === "") {
            document.write("Error: No tenant provided !")
            console.log("no tenant provided")
            return
        }

        const url = "/oauth2/" + params.get('tenant') + "/userinfo"

        const xhr = new XMLHttpRequest()
        xhr.open("GET", url)

        xhr.setRequestHeader("Accept", "application/json")
        xhr.setRequestHeader("Content-Type", "application/json")

        xhr.onreadystatechange = function () {
           if (xhr.readyState === 4) {
              console.log(xhr.status)
              console.log(xhr.responseText)
              var json = JSON.parse(xhr.responseText)
              if (json != "") {
                  var user = json["preferredUsername"]
                  loginIntoApp(user)
              }
           }}

        xhr.send()
    }


    function loginIntoApp(user) {
        console.log("logging in ...")
        console.log(user)
    }

    login()
    </script>

    </body>
    </html>
  proxy_logout.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1 class="title">Logout ...</h1>

    <script>

    function logout() {
        const params = new URLSearchParams(window.location.search)
        const tenant = params.get('tenant')

        if (tenant == null || tenant === "") {
            document.write("Error: No tenant provided !")
            console.log("no tenant provided")
            return
        }

        logoutByTenant(tenant);
    }

    function logoutByTenant(tenantId) {
        doRequest("/oauth2/" + tenantId + "/sign_out");
        //doRequest("/oidc/auth/realms/tenant-" + tenantId + "/protocol/openid-connect/logout");
        window.location.href = "/oidc/auth/realms/tenant-" + tenantId + "/protocol/openid-connect/logout";
    }

    function doRequest(url) {
        const xhr = new XMLHttpRequest();
        xhr.open("GET", url);
        xhr.onreadystatechange = function () {
           if (xhr.readyState === 4) { console.log(xhr.responseText); }
        }
        xhr.send();
    }

    logout()
    </script>

    </body>
    </html>
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-26T09:39:15Z"
  name: welcome-board-data-files
  resourceVersion: "27151"
  uid: 372ea9e1-be81-4e1b-9ca3-24837f0d6152
