apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 240
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}{{ .Values.image.arch }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: {{ include "application.fullname" . }}-config
            - configMapRef:
                name: {{ include "application.fullname" . }}-config-log
            - secretRef:
                name: {{ include "application.fullname" . }}-config-external

          #resources and commands and args
          {{- with .Values.resourcesAnnotations }}
            {{- toYaml . | nindent 10 }}
            {{- end }}

          volumeMounts:
            - mountPath: /usr/share/logs
              name: {{ include "application.fullname" . }}-applogs

      volumes:
        - name: {{ include "application.fullname" . }}-applogs
          emptyDir: {}
